name: Run Hello-World from py Script
on: push

jobs:
   Python-Script:
      runs-on: ubuntu-latest

      steps:
      - name: clone repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Run Python Script
        run: python Basic.py