name: Flask Deployment
on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Deploy in EC2
      env: 
        PRIVATE_KEY: ${{secrets.EC2_SSH_KEYS}}
        HOST_NAME: ${{secrets.EC2_HOST_NAME}}
        USER_NAME: ${{secrets.EC2_USER_NAME}} 
